### ISSUE TITLE
bridge/uds: confirm protocol design for unix-socket producers

### ISSUE THREAD

**Issue by lucab** [lucab/local_exporter#15]
This exporter currently defines a unix-socket protocol, which must me stabilized in order to be implemented by relevant producers.

The current protocol is by the design the simplest that I could imagine. It just expects producers to spit out Prometheus textual format to each new client connection, and then close the connection.

This waits on @pgier and @simonpasquier for protocol design review.

**Comment by lucab** [comment]
Once this is resolved, it will unblock https://github.com/coreos/zincati/issues/74.

**Comment by simonpasquier** [comment]
:+1: I don't think we need anything more fancy than a transparent proxy between the producer and Prometheus.

**Comment by lucab** [comment]
This is even a bit less than a transparent proxy, as it doesn't speak HTTP over the unix-domain socket.
That is intentional, in order to avoid:
 * a requirement on producers to implement a full HTTP stack
 * the quirkness of HTTP-over-UDS (what's the hostname? how is the uds path specified in the URL?)

**Comment by simonpasquier** [comment]
Yes I didn't mean proxy in the sense of network proxy.

**Comment by lucab** [comment]
Nothing major came up in a few month of usage, sticking to this. Closing.
